pipeline{
    agent any
    stages{
        stage('uptime'){
            steps{
                sh '''
                    uptime
                '''
            }
        }
        stage('RAM-Used'){
            steps{
                sh '''
                    free -h
                '''
            }
        }
        stage('disk-file'){
            steps{
                sh '''
                    df -kh
                '''
            }
        }
        stage('disk-usage'){
            steps{
                sh '''
                    du -x
                '''
            }
        }
        stage('poll-scm-checkin'){
            steps{
                sh '''
                    echo "git update checking for every minute"
                '''
            }
        }
    }
}